app/models/user.rb, db/migrate/20191126100718_add_columns_to_user.rb, db/migrate/20191126103317_add_picture_to_user.rb, db/schema.rb
-- données crées par devise -- 
Le modèle USER est déjà créé avec devise.
Il faut ajouter de nouvelles colonnes à la table
-- Nos actions-- 
- Création du fichier de migration pour ajouter les 3 colonnes à notre table USER : name, city et bio
-     Rails db:migrate pour ajouter les 3 colonnes au schéma
-     Création des validations dans le model USER
-     Ajout des références avec les modèles SEEDPACK et ORDER => destroy les deux si le user est supprimé
-- Next step -- 
Il faudra créer les authentification keys pour créer une nouvelle instance sans les valeurs nom et city qui sont obligatoires
A confirmer!
=> initializing user-model + validation + new columns

app/models/seedpack.rb, db/migrate/20191126102223_create_seedpacks.rb, db/schema.rb, test/models/seedpack_test.rb
Creation du model seedpack avec attribut: name, / number / description / image / price et foreign key: user_id.
rails db:migrate
contrôle les liens  belong to
crash test model (creation et sauvegarde)
ecriture des validates
=> model seedpack

db/json-flowers.json, db/seeds.rb
Création d'un seed à partir d'un JSON pour la table seedpack. 
Tester dans le terminal ==> OK 
Longueur db = 34
=> Seed file OK. Waiting for the controller and routes to crash test it

app/controllers/application_controller.rb, app/controllers/seedpacks_controller.rb, app/models/order.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/seedpacks/index.html.erb, app/views/seedpacks/new.html.erb, app/views/seedpacks/show.html.erb, config/routes.rb, db/seeds.rb, test/controllers/seedpacks_controller_test.rb
----- Mercredi ------ 
=> controller seedpack/view
- Seed : nouvelle instance user + seedpack pour test  - OK 
- Ajout dans controller et devise/registration/new des paramètres validates du user (name et city) -  OK 
- ControllerSeedpack #index : OK
- ControllerSeedpack #show :  OK
- ControllerSeedpack #new : OK
- Seedpacks/View/show :  Button Buy A AJOUTER
- Devise/registration/new : Autocomplete City  - A TESTER
---- Mardi ---- 
Routes: finalisées 
Controller Seedpack  - finalisé pour le moment
View : Index - A TESTER
View : new : formulaire  - A VERIFIER
view show: ajout du formulaire du seedpack - A COMPLETER avec bouton Buy
// Ajout des inputs du User (name et city)  -  pour faire fonctionner le log in/sign up - dans devise/view/seedpack/new - A TESTER
=> creation controllers_ view_routes

app/controllers/orders_controller.rb, app/models/order.rb, app/models/seedpack.rb, app/models/user.rb, config/routes.rb, test/controllers/orders_controller_test.rb
Création du controller Orders avec seulement la méthode Create.
- Dans le fichier model Order correction d'un bug sur le scope du validates : il manquait les " : "
- Dans le fichier model Seedpack ajout de la dépendance has_many orders
- Dans le fichier Routes ajout de la route resources :order uniquement pour l'action create
=> Order route controler

app/views/seedpacks/index.html.erb, app/views/seedpacks/new.html.erb, app/views/seedpacks/show.html.erb, db/seeds.rb
corrections des bugs: 
- Seedpack model : erreurs de syntaxe
-Seedpack view: mise en commentaire du render de la view/new
Toujours le pb sur l'affichage de notre seed. - " /home/anise/code/Anne-Lise/seedr/app/models/order.rb:8: syntax error, unexpected >>, expecting end
>>>>>>> 9cc2879a566c2b9d5eb1229...
"  ces modifications ne sont plus visibles dans le fichier seed mais s'affiche dans le terminal.
=> Corrections seedpacks

db/seeds.rb
modification du fichier seed - erreur du user dans la partie json
=>  Seed corrections - modification de la variable user dans json

app/views/pages/dashboard.html.erb, app/views/seedpacks/index.html.erb
creation du lien type bouton de l'index (seedpacks) vers dashboard
=> creation du bouton et lien vers dasboard depuis seedpacks

app/assets/stylesheets/config/_fonts.scss, app/views/seedpacks/index.html.erb
€ ajouté sur les cards de l'index
=> Symbole euro index

app/assets/stylesheets/config/_fonts.scss
ajout de la font Roboto dans app/stylsheets/config/_fonts.scss
@import url('https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap');
=> Police roboto

app/views/shared/_navbar.html.erb
ajout lien dashboard dans navbar + lien home sous onglet home
=> ajout lien dashboard dans navbar

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_new.scss, app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/seedpacks/new.html.erb
creation du fichier _new.scss pour améliorer le formulaire sur new.html.erb
=> Style home

app/controllers/orders_controller.rb, app/controllers/seedpacks_controller.rb, app/views/orders/confirmation.html.erb, app/views/pages/dashboard.html.erb, app/views/seedpacks/index.html.erb, app/views/seedpacks/show.html.erb, config/routes.rb
- ajout d'un CTA "buy"
- création d'un order
- redirection vers une view de confirmation
- ajout du seedpack acheté dans le dashboard, rubrique "achat"
- retrait du seedpack acheté de l'index
=> Order - Achat d'un seedpack

app/views/seedpacks/show.html.erb
début de code css  dans le show
=> ajout début de code css dans show

app/views/devise/registrations/new.html.erb
on peut à présent commencer à inscrire la ville dans la catégorie city et si elle est déjà créée, elle apparaît dans la dropbox
http://www.localhost:3000/users/sign_up
=> autocomplete-city résolu

app/controllers/seedpacks_controller.rb, app/views/pages/dashboard.html.erb, app/views/seedpacks/_form.html.erb, app/views/seedpacks/edit.html.erb, app/views/seedpacks/new.html.erb, app/views/seedpacks/show.html.erb
- Ajout dans controller  + view seedpack des méthodes edit et destroy 
-factorisation formulaire dans partial _form
- ajout placeholder
=> ajout actions edit et destroy dans controller + view seedpacks

app/views/seedpacks/_form.html.erb, app/views/seedpacks/new.html.erb
debugage code html  dans seedpack view
=> debugage html dans view

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_btn.scss, app/assets/stylesheets/components/_cardseed.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/views/seedpacks/index.html.erb, app/views/shared/_navbar.html.erb
Style des composants suivants :
- navbar
- seedpack-index-cards
- btn-add-seed-home
- btn-add-seed-dashboard
- btn buy
- btn-back
- footer
Liaisons dans le fichier _index.scss
=> components css

app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_index.scss, app/views/pages/dashboard.html.erb
frontend dashboard - html - 3 boxes
=> Dashboard flexbox

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_show.scss, app/views/seedpacks/show.html.erb
structure html et mise en flexbox et... c'est tout!!!
=> Customize seedshow
